
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cafe-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mugitya # ★後で使うので覚えておく
      MYSQL_DATABASE: cafe_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: